### ISSUE TITLE
Can't use with android 6.0

### ISSUE THREAD

**Issue by zerob13** [JackyYuanOne/TwitterSearchDemo#1]
```
FATAL EXCEPTION: main
Process: com.yuan.twittersearchdemo, PID: 8609
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yuan.twittersearchdemo/com.yuan.twittersearchdemo.MainActivity}: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)
  at android.app.ActivityThread.-wrap11(ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5466)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
  Caused by: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
  at android.os.Parcel.readException(Parcel.java:1620)
  at android.os.Parcel.readException(Parcel.java:1573)
  at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:606)
  at android.location.LocationManager.requestLocationUpdates(LocationManager.java:892)
  at android.location.LocationManager.requestLocationUpdates(LocationManager.java:465)
  at com.yuan.twittersearchdemo.MainActivity.initLocation(MainActivity.java:207)
  at com.yuan.twittersearchdemo.MainActivity.onCreate(MainActivity.java:167)
  at android.app.Activity.performCreate(Activity.java:6251)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520) 
  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
  at android.os.Handler.dispatchMessage(Handler.java:102) 
  at android.os.Looper.loop(Looper.java:148) 
  at android.app.ActivityThread.main(ActivityThread.java:5466) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

```

**Comment by JackyMR** [comment]
I got,and fix the bug.
